language: python
sudo: false
python:
    - "2.7"
branches:
    only:
        - master
        - /^v[0-9].*$/
addons:
    apt:
        packages:
            - gfortran
before_install:
    # Install conda
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
    - conda config --add channels conda-forge
    - conda update -q conda
    - conda info -a
    - conda install conda-env  # no longer installed by default?
install:
    # Edit in the correct Python version into environment.yaml
    - sed -i "s/- python/- python=${TRAVIS_PYTHON_VERSION}/g" environment.yaml
    # Create conda matching requirements
    - conda env create -n test -f environment.yaml
    - source activate test
    - pip install rpy2  # temp fix for broken ICU with conda-forge & r channels
    # Rest of dependencies
    - "pip install -r tests/requirements.txt"
    # Install YATSM
    - "pip install -e ."
    # Info
    - conda env export
script:
    - py.test -ra tests/
    # Disable numba JIT for coverage to correctly identify JIT-ed lines
    # See: http://stackoverflow.com/questions/26875191/analyzing-coverage-of-numba-wrapped-functions
    - NUMBA_DISABLE_JIT=1 coverage run --source yatsm -m py.test
after_success:
    # Report coverage
    - pip install coveralls
    - coverage report
    - coveralls
after_script:
    # Docs
    - source activate test
    - conda install python-graphviz
    - pip install -r docs/requirements-docs.txt
    - sphinx-apidoc -f -e -o docs/source/yatsm yatsm/
    - bash docs/scripts/deploy-to-gh-pages.sh
before_cache:
    # Deactivate conda so we use system 'curl'
    - source deactivate
env:
    global:
        - ENCRYPTION_LABEL: "f7129f342355"
        - COMMIT_AUTHOR_EMAIL: "ceholden@gmail.com"
        - COMMIT_AUTHOR_NAME: "Chris Holden"
notifications:
    email: false
