# Conda environment file for YATSM
# Includes optional dependencies since conda makes installing them pretty easy
name: yatsm
channels:
    - r
    - conda-forge
dependencies:
    # Base
    - python
    - numpy>=1.9.0
    - scipy>=0.14.0
    - Cython>=0.20.1
    # Statistics
    - statsmodels>=0.5.0
    - scikit-learn>=0.15.1
    - pandas>=0.16.0
    - patsy>=0.3.0
    # GDAL and IO
    - fiona>=1.7.0
    - gdal>=1.11
    - rasterio>=1.0*
    - shapely>=1.5.16
    - xarray>=0.7.1
    - pytables>=3.2.0
    # CLI
    - click>=4.0
    # Config file
    - pyyaml>=3.11
    - jsonschema>=2.5.1
    # Plotting
    - matplotlib>=1.4.2
    # Accelerated functions w/ numba (OPTIONAL)
    - numba>=0.27.0
    # Python interface to R (OPTIONAL)
    - rpy2>=2.5.6
    - pip:
        # GLMNET (OPTIONAL)
        - git+git://github.com/ceholden/glmnet-python.git@v2.0.1
        # Required but missing from conda
        - palettable>=2.0.0
        - click_plugins>=1.0
        - decorator>=4.0.10
        - toposort>=1.4
